[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
anchor_project = "2pXtF9SQ6nbLkckCd2uFKg9somxmivYMMCE2V4LhJowR"

[programs.localnet]
anchor_project = "Anchor1111111111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
# wallet = "/Users/emilemilovroydev/phantomWallet.json"
wallet = "~/.config/solana/id.json"

[cluster]
localnet = "http://127.0.0.1:8899"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
